export default[{
    id: 1,
    title: 'Boa Lab',
    description: "Website about Boa Lab, a company that provides architecture and design solutions",
    img: "https://meryboth.github.io/marilynb/assets/img/work1.jpg",
    url: "https://boa-lab.netlify.app/",
    repositorio: "https://github.com/meryboth/boa-lab",
    javascript: false,
    html: true,
    css: true,
    react: false,
},{
    id: 2,
    title: 'Tarantino App',
    description: "Web app with a quiz about filmaker Quentin Tarantino and some of his best movies",
    img: "https://meryboth.github.io/marilynb/assets/img/work2.jpg",
    url: "https://meryboth.github.io/tarantino-app/",
    repositorio: "https://github.com/meryboth/tarantino-app",
    javascript: true,
    html: true,
    css: true,
    react: false,
},{
    id: 3,
    title: 'Countdown',
    description:"A simple countdown timer set with next New Year's Eve date and made with Javascript",
    img: "https://meryboth.github.io/marilynb/assets/img/work3.jpg",
    url: "https://codepen.io/meryboth/pen/QWNOGax",
    repositorio: "https://codepen.io/meryboth/pen/QWNOGax",
    javascript: true,
    html: true,
    css: true,
    react: false,
}, {
    id: 4,
    title: 'Waterspring Festival',
    description: "A fanmade website about the Waterspring Festival, a festival that takes place in London",
    img: "https://meryboth.github.io/marilynb/assets/img/work4.jpg",
    url: "https://meryboth.github.io/watersprite-film-festival/",
    repositorio:"https://github.com/meryboth/watersprite-film-festival",
    javascript: false,
    html: true,
    css: true,
    react: false,  
}, {
    id: 5,
    title: 'Flaneur',
    description: "Website about travel, places and culture thought the lens of a flaneur. If you love to travel you will like it",
    img: "https://meryboth.github.io/marilynb/assets/img/work5.jpg",
    url: "https://meryboth.github.io/flaneur/",
    repositorio: "https://github.com/meryboth/flaneur",
    javascript: false,
    html: true,
    css: true,
    react: false,
}, {
    id: 6,
    title: 'Art Corner',
    description: "Ecommerce website about online digital art made with Javascript. You can buy prints and artworks",
    img: "https://meryboth.github.io/marilynb/assets/img/work6.jpg",
    url: "https://art-corner.netlify.app/",
    repositorio: "https://github.com/meryboth/Art-Corner-E-Commerce",
    javascript: true,
    html: true,
    css: true,
    react: false,
}, {
    id: 7,
    title: 'Movie App',
    description: "Movie search app made with React, choose your favorite movies and see the details",
    img: "https://tritonvoice.co/wp-content/uploads/2019/03/GKKFYsUV3HipHYUtKTrUPeiz.png",
    url: "https://movie-app-meryboth.vercel.app/",
    repositorio: "https://github.com/meryboth/movie-app",
    javascript: false,
    html: true,
    css: true,
    react: true,
}, {
    id: 8,
    title: 'Meme Generator',
    description: "Meme generator made with React and the Api´s Meme. It allows you to create your own memes",
    img: "https://i.blogs.es/d86db0/meme-fry-1/450_1000.jpg",
    url: "https://meme-ten.vercel.app/",
    repositorio: "https://github.com/meryboth/meme-generator",
    javascript: false,
    html: true,
    css: true,
    react: true,
}, {
    id: 9,
    title: 'Music App',
    description: "Fanmade music website made with React using React Router and dinamic components",
    img: "https://meryboth.github.io/marilynb/assets/img/music-app.jpg",
    url: "https://music-website-delta.vercel.app/",
    repositorio: "https://github.com/meryboth/music-website",
    javascript: false,
    html: true,
    css: true,
    react: true,
}]